### ISSUE TITLE
sistemare yarn

### ISSUE THREAD

**Issue by xrmx** [tohacknight/open-hospital#1]

**Comment by AceGentile** [comment]
Possiamo pensare anche che `"install:types": "yarn typesync"` non serva più?

**Comment by AceGentile** [comment]
Allineato `package-lock.json` qui https://github.com/informatici/openhospital-ui/pull/8

**Comment by AceGentile** [comment]
PR per rimuovere yarn.lock https://github.com/informatici/openhospital-ui/pull/12
