### ISSUE TITLE
npm test fail with SyntaxError

### ISSUE THREAD

**Issue by baldoalessandro** [tohacknight/open-hospital#10]
```
 Details:

    /home/ale-td/Documents/oss/open-hospital/openhospital-ui/node_modules/react-day-picker/lib/style.css:3
    .DayPicker {
    ^

    SyntaxError: Unexpected token .

      15 | import * as React from "react";
      16 | import DayPicker from "react-day-picker";
    > 17 | import "react-day-picker/lib/style.css";
         | ^
      18 | import { Link as LinkRouter } from "react-router-dom";
      19 | import styles from "./Calendario.style";
      20 | import ExpandMore from "@material-ui/icons/ExpandMore";

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)
      at Object.<anonymous> (src/components/calendar/Calendario.tsx:17:1)
      at Object.<anonymous> (src/routes.tsx:17:1)
```

**Comment by baldoalessandro** [comment]
https://github.com/wmonk/create-react-app-typescript is deprecated, a possible migration is described here https://vincenttunru.com/migrate-create-react-app-typescript-to-create-react-app/

**Comment by AceGentile** [comment]
@baldoalessandro non è che jest non sa come gestirsi i css e va settato il `moduleNameMapper` facendogli gestire il css?

**Comment by baldoalessandro** [comment]
si può essere stavo provando pure quello, ma faccio il mock dei moduli css?

**Comment by AceGentile** [comment]
Dunque ci sono un po' di casini tutti insieme:

- `setupTestFrameworkScriptFile` è stato deprecato e sostituito da `setupFilesAfterEnv`
- vanno settati i `moduleNameMapper`, soprattutto per il css
- "Version 24.1.0 of jest installed has not been tested with ts-jest"

**Comment by baldoalessandro** [comment]
Ho provato questo ma niente: https://github.com/facebook/jest/issues/3094#issuecomment-431564037

**Comment by baldoalessandro** [comment]
Provato con 1, 2 (https://github.com/facebook/jest/issues/3094#issuecomment-385164816) e 3 (v 23.6.0) senza successo.

**Comment by AceGentile** [comment]
A quanto pare non c'erano solo quelle cose ma richiedeva anche altri fix per funzionare:

https://github.com/informatici/openhospital-ui/pull/14
