### ISSUE TITLE
aggiornare dipendenze

### ISSUE THREAD

**Issue by xrmx** [tohacknight/open-hospital#2]
- [X] npm audit
- [x] Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

**Comment by AceGentile** [comment]
Allineato `package-lock.json` qui informatici/openhospital-ui#8

**Comment by xrmx** [comment]
https://github.com/informatici/openhospital-ui/pull/19 browserslist qua
